application: epoisom
version: 1
runtime: python
api_version: 1

handlers:
- url: /jslib
  static_dir: jslib

- url: /icon/.*
  script: epoicons.py

- url: /epoiadmin
  script: epoiadmin.py

- url: /login
  script: epoiadmin.py

- url: /logout
  script: epoiadmin.py

- url: /.*
  script: main.py

